<a href="https://colab.research.google.com/github/AaronYounger/Machine-Learning/blob/main/Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(0)

df = pd.read_csv("dataset.csv")
x = df[['a','b']]
# y = df['C']

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases
    return self.output

class Activation_ReLU:
    def forward(self, inputs):
      self.output = np.maximum(0, inputs)
      return self.output
# return instead of print so I can keep using this function within the code


layer1 = Layer_Dense(2, 5)
aa1 = Activation_ReLU()
layer2 = Layer_Dense(5, 3)
aa2 = Activation_ReLU()
layer3 = Layer_Dense(3, 1)

# Forward Pass

layer1 = layer1.forward(x)
aa1 = aa1.forward(layer1)

layer2 = layer2.forward(aa1)
aa2 = aa2.forward(layer2)

layer3 = layer3.forward(aa2)

print("Layer1 output:\n", layer1)
print("Layer2 output:\n", layer2)
print("Layer3 output:\n", layer3)



Layer1 output:
 [[-0.08146919  0.08207245 -0.01166037 -0.00581697  0.03776845]
 [ 0.06020172  0.07632952  0.05430682  0.13735393  0.14103284]
 [-0.00090654  0.04674439  0.01515779  0.0444543   0.05694652]
 [ 0.1642217   0.04381631  0.09330369  0.21498882  0.18195353]
 [ 0.06534662  0.02813926  0.04069759  0.09594529  0.0856043 ]
 [ 0.00396447  0.09864895  0.03480519  0.09998726  0.12475751]
 [-0.07044321  0.08020888 -0.00699879  0.0039497   0.04405814]
 [ 0.0961467   0.03568748  0.05797351  0.1356164   0.11890415]]
Layer2 output:
 [[ 0.00426346  0.00083985  0.01131106]
 [ 0.01036982 -0.03450447  0.04981737]
 [ 0.0039593  -0.01381167  0.01786536]
 [ 0.01420557 -0.04447741  0.07223202]
 [ 0.0065695  -0.02093075  0.03288741]
 [ 0.00870221 -0.03054456  0.03953526]
 [ 0.00444714 -0.00071802  0.01293464]
 [ 0.00917643 -0.02907036  0.04617536]]
Layer3 output:
 [[-0.00082794]
 [-0.00244065]
 [-0.00091024]
 [-0.00341808]
 [-0.00157104]
 [-0.00200566]
 [-0.00088889]
 [-0.00219892]]
